---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: portfolio/my-life
  label: My Life
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - journal
- type: directory
  path: portfolio/works
  label: Works
  create: all
  match: "**/*"
  templates:
  - works
- type: directory
  path: portfolio/journal
  label: Journal
  create: all
  match: "**/[!index]*"
  templates:
  - journal
- type: heading
  label: Theme settings
- type: directory
  path: portfolio
  label: General
  create: none
  match: index.md
  templates:
  - settings
upload_dir: portfolio/.vuepress/public/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
